[supervisord]  ## This is the main process for the Supervisor    
nodaemon=true  ## This setting is to specify that we are not running in daemon mode

[program:unbound]
command=/usr/sbin/unbound -d
autostart=true
stderr_logfile=/dev/stdout
stderr_logfile_maxbytes = 0
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes = 0

[program:cache-load]
command=cat /var/lib/unbound/unbound.cache | /usr/sbin/unbound-control load_cache
autostart=false
stderr_logfile=/var/lib/unbound/cache.log
stderr_logfile_maxbytes = 0
stdout_logfile=/var/lib/unbound/cache.log
stdout_logfile_maxbytes = 0
